### ISSUE TITLE
Gen 7 megas broken on switch

### ISSUE THREAD

**Issue by attraylor** [hsahovic/poke-env#103]
Once a Pokemon mega-evolves and then switches back in the order crashes:

2020-12-08 16:20:49,439 - Random player - WARNING - Error message received: |error|[Invalid choice] Can't switch: You do not have a Pokémon named "latiasmega" to switch to
Traceback (most recent call last):
  File "examples/BigBoy/pytorch_gym.py", line 448, in <module>
    env_algorithm_kwargs={"nb_steps": NB_TRAINING_STEPS},
  File "/Users/aaron/Documents/Pokemon/poke-env/src/poke_env/player/env_player.py", line 351, in play_against
    loop.run_until_complete(launch_battles(self, opponent))
  File "/Users/aaron/miniconda3/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/Users/aaron/miniconda3/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/Users/aaron/miniconda3/lib/python3.7/asyncio/base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/aaron/miniconda3/lib/python3.7/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)

This happens for every mega (Testing in gen 7 random single battles)

**Comment by hsahovic** [comment]
Hey @attraylor,

Thanks for opening this issue. I'll look into it and try to get a patch sometime this week :)

**Comment by hsahovic** [comment]
I've looked into it, first with `RandomPlayer`, then using the gen 7 example rl script, without any issue. I confirmed that the rl player played games where it mega-evolved and switched out and in its mega several times.
Is your code modifying the way species and / or move creation is managed?
