### ISSUE TITLE
[Bug Report] NotImplementedError

### ISSUE THREAD

**Issue by lolanchen** [hsahovic/poke-env#169]
```
2021-05-31 14:37:30,990 - Env17041 - ERROR - Unhandled exception raised while handling message:
>battle-gen8randombattle-5118555
|
|t:|1622439450
|switch|p2a: Passimian|Passimian, L82, F|100/100
|-activate|p2a: Passimian|move: Sticky Web
|-unboost|p2a: Passimian|spe|1
|split|p2
|-damage|p2a: Passimian|280/298|[from] Stealth Rock
|-damage|p2a: Passimian|94/100|[from] Stealth Rock
|move|p1a: Bellossom|Strength Sap|p2a: Passimian
|-unboost|p2a: Passimian|atk|1
|-ability|p2a: Passimian|Defiant
|-boost|p2a: Passimian|atk|2
|-heal|p1a: Bellossom|257/257
|
|upkeep
|turn|27
Traceback (most recent call last):
  File "/home/chen/research/pfrl/dependencies/poke-env/src/poke_env/player/player_network_interface.py", line 131, in _handle_message
    await self._handle_battle_message(split_messages)
  File "/home/chen/research/pfrl/dependencies/poke-env/src/poke_env/player/player.py", line 301, in _handle_battle_message
    battle._parse_message(split_message)
  File "/home/chen/research/pfrl/dependencies/poke-env/src/poke_env/environment/abstract_battle.py", line 458, in _parse_message
    raise NotImplementedError(split_message)
NotImplementedError: ['', 'split', 'p2']
```

**Comment by lolanchen** [comment]
and related but here's one more
```
2021-05-31 15:04:10,374 - poke-env - WARNING - Unexpected effect 'Vital_Spirit' received. Effect._UNKNOWN will be used instead. If this is unexpected, please open an issue at https://github.com/hsahovic/poke-env/issues/ along with this error message and a description of your program.
```
