### ISSUE TITLE
ValueError: Error when checking input: expected dense_input to have 3 dimensions, but got array with shape (10, 1 )

### ISSUE THREAD

**Issue by IndigoGems** [hsahovic/poke-env#178]
The error seems to be caused from this part of the code

File "cleanTrained.py", line 33, in choose_move
    predictions = self.model.predict([state])[0]

This is the part of the code for the predictions to occur.

```python
# Load in trained model

class TrainedRLPlayer(Player):
  def __init__(self, model = tf.keras.models.load_model('E:\ShowdownBot\model_10000'), *args, **kwargs):
    Player.__init__(self, *args, **kwargs)
    self.model = model
    
  def choose_move(self, battle):
    state = TrainedRLPlayer.embed_battle(self, battle)
    #target_f = self.model.predict( [ np.array(state[0]), np.array(state[1]) ] )
    predictions = self.model.predict([state])[0]
    action = np.argmax(predictions)
    return TrainedRLPlayer._action_to_move(action)
```

**Comment by hsahovic** [comment]
Can you `print(model.summary())`? I suspect it's `keras-rl` doing some weird model reshaping.

**Comment by IndigoGems** [comment]
Here are the results from **print(model.summary())**

```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 1, 128)            1408
_________________________________________________________________
flatten (Flatten)            (None, 128)               0
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256
_________________________________________________________________
dense_2 (Dense)              (None, 22)                1430
=================================================================
Total params: 11,094
Trainable params: 11,094
Non-trainable params: 0
_________________________________________________________________
None
```

**Comment by hsahovic** [comment]
Ah, the sequential model does not show the input later.
If you print `model.input`?

As a wild guess, you might want to try to reshape the state:

```python
    state = TrainedRLPlayer.embed_battle(self, battle)
    predictions = self.model.predict(
        state.reshape(1, -1, 1) # or maybe (1, 1, -1)?
    )
```

**Comment by IndigoGems** [comment]
After messing around with the code a little an error message that might be unrelated pops up:

```
Traceback (most recent call last):
  File "E:\ShowdownBot\venv\lib\site-packages\poke_env\player\player_network_interface.py", line 131, in _handle_message
    await self._handle_battle_message(split_messages)
  File "E:\ShowdownBot\venv\lib\site-packages\poke_env\player\player.py", line 295, in _handle_battle_message
    await self._handle_battle_request(battle)
  File "E:\ShowdownBot\venv\lib\site-packages\poke_env\player\player.py", line 316, in _handle_battle_request
    message = self.choose_move(battle).message
AttributeError: 'NoneType' object has no attribute 'message'

```

**Comment by hsahovic** [comment]
Can you copy-paste your current script?
