### ISSUE TITLE
Issue installing pokemon-showdown for poke-env

### ISSUE THREAD

**Issue by mnguyen0226** [hsahovic/poke-env#188]
Hi,
Pokemon-master branch get updates frequently which can be a problem for compatibility problem wise for poke-env. I install node js v14+ and just try to run node pokemon-showdown start --no-security to test server but got this issue

------------------------------------------------------------
~/Documents/pokemon-showdown$ node pokemon-showdown start --no-security
Error: Cannot find module '../config/config'
Require stack:
- /home/mnguyen/Documents/pokemon-showdown/server/config-loader.ts
- /home/mnguyen/Documents/pokemon-showdown/server/index.ts
- /home/mnguyen/Documents/pokemon-showdown/pokemon-showdown
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.<anonymous> (/home/mnguyen/Documents/pokemon-showdown/server/config-loader.ts:23:29)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (/home/mnguyen/Documents/pokemon-showdown/node_modules/ts-node/src/index.ts:1311:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/home/mnguyen/Documents/pokemon-showdown/node_modules/ts-node/src/index.ts:1314:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mnguyen/Documents/pokemon-showdown/server/config-loader.ts',
    '/home/mnguyen/Documents/pokemon-showdown/server/index.ts',
    '/home/mnguyen/Documents/pokemon-showdown/pokemon-showdown'
  ]
}
(pokebot) mnguyen@HeronLoaner2:~/Documents/pokemon-showdown$ Error: Cannot find module '../config/config'
Require stack:
- /home/mnguyen/Documents/pokemon-showdown/server/config-loader.ts
- /home/mnguyen/Documents/pokemon-showdown/server/team-validator-async.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.<anonymous> (/home/mnguyen/Documents/pokemon-showdown/server/config-loader.ts:23:29)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (/home/mnguyen/Documents/pokemon-showdown/node_modules/ts-node/src/index.ts:1311:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/home/mnguyen/Documents/pokemon-showdown/node_modules/ts-node/src/index.ts:1314:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mnguyen/Documents/pokemon-showdown/server/config-loader.ts',
    '/home/mnguyen/Documents/pokemon-showdown/server/team-validator-async.ts'
  ]
}
------------------------------------------------------------
=> Any one has this problem before? What pokemon-showdown branch works for you?

Thanks!

**Comment by mingu600** [comment]
As stated [here](https://github.com/smogon/pokemon-showdown/blob/master/server/README.md), you need to copy config/config-example.js into config/config.js in the showdown repo and edit accordingly.

**Comment by hsahovic** [comment]
Hey @mnguyen0226,

Thanks for bringing this up, and sorry for the delay in response! As @mingu600 stated, this is due to a change in the way config files are dealt with in pokemon showdown. I will update `poke-env`'s docs to mirror this change.
