### ISSUE TITLE
Build error with newer setuptools>58.5.3

### ISSUE THREAD

**Issue by acxz** [hsahovic/poke-env#252]
Command: `python setup.py build`

Error Log:
```
running build
running build_py
creating build
creating build/lib
creating build/lib/poke_env
copying src/poke_env/player_configuration.py -> build/lib/poke_env
copying src/poke_env/__init__.py -> build/lib/poke_env
copying src/poke_env/exceptions.py -> build/lib/poke_env
copying src/poke_env/server_configuration.py -> build/lib/poke_env
copying src/poke_env/data.py -> build/lib/poke_env
copying src/poke_env/utils.py -> build/lib/poke_env
creating build/lib/poke_env/teambuilder
copying src/poke_env/teambuilder/constant_teambuilder.py -> build/lib/poke_env/teambuilder
copying src/poke_env/teambuilder/__init__.py -> build/lib/poke_env/teambuilder
copying src/poke_env/teambuilder/teambuilder.py -> build/lib/poke_env/teambuilder
copying src/poke_env/teambuilder/teambuilder_pokemon.py -> build/lib/poke_env/teambuilder
creating build/lib/poke_env/environment
copying src/poke_env/environment/__init__.py -> build/lib/poke_env/environment
copying src/poke_env/environment/battle.py -> build/lib/poke_env/environment
copying src/poke_env/environment/pokemon.py -> build/lib/poke_env/environment
copying src/poke_env/environment/effect.py -> build/lib/poke_env/environment
copying src/poke_env/environment/move_category.py -> build/lib/poke_env/environment
copying src/poke_env/environment/side_condition.py -> build/lib/poke_env/environment
copying src/poke_env/environment/abstract_battle.py -> build/lib/poke_env/environment
copying src/poke_env/environment/field.py -> build/lib/poke_env/environment
copying src/poke_env/environment/pokemon_type.py -> build/lib/poke_env/environment
copying src/poke_env/environment/status.py -> build/lib/poke_env/environment
copying src/poke_env/environment/move.py -> build/lib/poke_env/environment
copying src/poke_env/environment/z_crystal.py -> build/lib/poke_env/environment
copying src/poke_env/environment/weather.py -> build/lib/poke_env/environment
copying src/poke_env/environment/pokemon_gender.py -> build/lib/poke_env/environment
copying src/poke_env/environment/double_battle.py -> build/lib/poke_env/environment
creating build/lib/poke_env/player
copying src/poke_env/player/__init__.py -> build/lib/poke_env/player
copying src/poke_env/player/player.py -> build/lib/poke_env/player
copying src/poke_env/player/baselines.py -> build/lib/poke_env/player
copying src/poke_env/player/battle_order.py -> build/lib/poke_env/player
copying src/poke_env/player/utils.py -> build/lib/poke_env/player
copying src/poke_env/player/random_player.py -> build/lib/poke_env/player
copying src/poke_env/player/env_player.py -> build/lib/poke_env/player
copying src/poke_env/player/trainable_player.py -> build/lib/poke_env/player
copying src/poke_env/player/player_network_interface.py -> build/lib/poke_env/player
running egg_info
creating src/poke_env.egg-info
writing src/poke_env.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/home/acxz/vcs/git/github/acxz/poke-env/setup.py", line 95, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 46, in run
    self.build_package_data()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 113, in build_package_data
    for package, src_dir, build_dir, filenames in self.data_files:
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 55, in __getattr__
    self.data_files = self._get_data_files()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 67, in _get_data_files
    self.analyze_manifest()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 131, in analyze_manifest
    self.run_command('egg_info')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.10/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 167, in write_pkg_file
    write_field('Summary', single_line(self.get_description()))
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 151, in single_line
    raise ValueError('Newlines are not allowed')
ValueError: Newlines are not allowed
```

**Comment by hsahovic** [comment]
Thanks @acxz !
