### ISSUE TITLE
Issue running ai

### ISSUE THREAD

**Issue by godpow** [hsahovic/poke-env#286]
I know this probably the best place to put this but does anyone know how to fix this issue?
`2022-04-26 01:02:59.326598: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-26 01:02:59.739206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5547 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)
2022-04-26 01:02:59.831854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5547 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5
Training for 10000 steps ...
Interval 1 (0 steps performed)
C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
2022-04-26 01:03:02.246876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5547 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\poke_env\player\env_player.py", line 369, in <lambda>
    target=lambda: env_algorithm_wrapper(self, env_algorithm_kwargs)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\poke_env\player\env_player.py", line 353, in env_algorithm_wrapper
    env_algorithm(player, **kwargs)
  File "C:\Users\CyberKira\Downloads\showdownbot-main\rl_player_train.py", line 100, in dqn_training
    dqn.fit(player, nb_steps=nb_steps)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\rl\core.py", line 168, in fit
    action = self.forward(observation)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\rl\agents\dqn.py", line 224, in forward
    q_values = self.compute_q_values(state)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\rl\agents\dqn.py", line 68, in compute_q_values
    q_values = self.compute_batch_q_values([state]).flatten()
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\rl\agents\dqn.py", line 63, in compute_batch_q_values
    q_values = self.model.predict_on_batch(batch)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training_v1.py", line 1201, in predict_on_batch
    outputs = self.predict_function(inputs)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\backend.py", line 4275, in __call__
    fetched = self._callable_fn(*array_vals,
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\client\session.py", line 1480, in __call__
    ret = tf_session.TF_SessionRunCallable(self._session._session,
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) FAILED_PRECONDITION: Could not find variable Hidden2/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/Hidden2/kernel/class tensorflow::Var does not exist.
         [[{{node Hidden2/MatMul/ReadVariableOp}}]]
         [[Hidden2/BiasAdd/_31]]
  (1) FAILED_PRECONDITION: Could not find variable Hidden2/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/Hidden2/kernel/class tensorflow::Var does not exist.
         [[{{node Hidden2/MatMul/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.`

**Comment by godpow** [comment]
model.add(Flatten(name='Flatten1'))
    model.add(Dense(64, name='Hidden1', activation="elu"))
    model.add(Dense(n_action, name='Hidden2', activation="linear"))
