### ISSUE TITLE
Data transfer error using the latest version

### ISSUE THREAD

**Issue by Gummygamer** [hsahovic/poke-env#45]
When trying your solution to the other issue, I found out I couldn't even run what I could before because even the default gen 8 RL example causes a websocket error, here's the output:

2020-05-09 16:48:45.305242: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2020-05-09 16:48:45.334698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.695
pciBusID: 0000:01:00.0
2020-05-09 16:48:45.342867: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-05-09 16:48:45.349812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-05-09 16:48:45.355193: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-05-09 16:48:45.364441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.695
pciBusID: 0000:01:00.0
2020-05-09 16:48:45.372899: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-05-09 16:48:45.379697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-05-09 16:48:45.884026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-09 16:48:45.889310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2020-05-09 16:48:45.892619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2020-05-09 16:48:45.896443: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4614 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
Training for 10000 steps ...
Error in data transfer
Traceback (most recent call last):
  File "C:\Users\Darabat\Anaconda3\lib\site-packages\websockets\protocol.py", line 681, in transfer_data
    while len(self.messages) >= self.max_queue:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
Error in data transfer
Traceback (most recent call last):
  File "C:\Users\Darabat\Anaconda3\lib\site-packages\websockets\protocol.py", line 681, in transfer_data
    while len(self.messages) >= self.max_queue:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
Error in data transfer
Traceback (most recent call last):
  File "C:\Users\Darabat\Anaconda3\lib\site-packages\websockets\protocol.py", line 681, in transfer_data
    while len(self.messages) >= self.max_queue:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Darabat\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Darabat\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Darabat\Anaconda3\lib\site-packages\poke_env-0.3.1-py3.7.egg\poke_env\player\env_player.py", line 343, in <lambda>
    target=lambda: env_algorithm_wrapper(self, env_algorithm_kwargs)
  File "C:\Users\Darabat\Anaconda3\lib\site-packages\poke_env-0.3.1-py3.7.egg\poke_env\player\env_player.py", line 327, in env_algorithm_wrapper
    env_algorithm(player, **kwargs)
  File "pokerl.py", line 81, in dqn_training
    dqn.fit(player, nb_steps=nb_steps)
  File "C:\Users\Darabat\Anaconda3\lib\site-packages\rl\core.py", line 132, in fit
    observation = deepcopy(env.reset())
  File "C:\Users\Darabat\Anaconda3\lib\site-packages\poke_env-0.3.1-py3.7.egg\poke_env\player\env_player.py", line 150, in reset
    raise EnvironmentError("User %s has no active battle." % self.username)
OSError: User RL Player has no active battle.

**Comment by Gummygamer** [comment]
I just confirmed that this error doesn't happen with the previous version.

**Comment by hsahovic** [comment]
Hi,

Thanks for opening this issue. I suspect a version conflict: can you try running `pip install --upgrade websockets` and re-running the code?

**Comment by Gummygamer** [comment]
I hadn't tried with --upgrade, this time it worked with the newest poke-env, thanks a lot.

**Comment by hsahovic** [comment]
@Gummygamer thanks for reporting this result! I'm adding a version requirement to `websockets` in the next release :)
