### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ZacDavis0-159910538** [hsahovic/poke-env#87]
Hi! Cool Repository. I was following the installation guide for your custom server branch of Pokemon Showdown https://poke-env.readthedocs.io/en/stable/getting_started.html#installing-poke-env to start contributing/testing doubles.
However, when running: node pokemon-showdown, I got the following error:
Installing dependencies...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\node_modules\tar-stream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\node_modules\optimist\package.json'

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\node_modules\tar-fs\node_modules\tar-stream
npm ERR! dest C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\node_modules\tar-fs\node_modules\.tar-stream.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\node_modules\tar-fs\node_modules\tar-stream' -> 'C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\node_modules\tar-fs\node_modules\.tar-stream.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zac\AppData\Roaming\npm-cache\_logs\2020-11-06T07_59_47_328Z-debug.log
child_process.js:655
    throw err;
    ^

Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at shell (C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\build:19:16)
    at Object.<anonymous> (C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\build:66:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 4294963238,
  signal: null,
  output: [ null, null, null ],
  pid: 12848,
  stdout: null,
  stderr: null
}
child_process.js:655
    throw err;
    ^

Error: Command failed: node build
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at build (C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\pokemon-showdown:21:27)
    at Object.<anonymous> (C:\Users\zac\Dropbox\DesktopSaving\Desktop\cmc\College Classes Documents\CPSI040\Pokemon Battle Simulator\hsavovic\pokemon-showdown\pokemon-showdown:29:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12856,
  stdout: null,
  stderr: null
}

**Comment by hsahovic** [comment]
Hi @ZacDavis0-159910538,

Thanks for opening this issue. Which version of node are you running? Can you try upgrading it?

**Comment by hsahovic** [comment]
Hey @ZacDavis0-159910538, any update on this? Have you been able to make it work?
